### ISSUE TITLE
Pages Deployment 404

### ISSUE THREAD

**Issue by ManonLef** [ChargrilledChook/calculator#1]
Hi Chook! 

I was getting ready to play with your calculator that you recently turned public. I even had a nice cup of tea ready but then I was met with a 404 not found.

Kind regards,

Manon

**Comment by ChargrilledChook** [comment]
I wouldn't worry, it's not particularly good :sweat_smile: 

I think they've changed how gh-pages work since I originally did it :shrug: not sure why it's not working
